#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEVICE=pyramid

mkdir -p ../../../vendor/htc/$DEVICE/proprietary

adb pull /system/bin/snd8k ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/bin/sound8x60 ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/etc/AdieHWCodecSetting.csv ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/etc/AudioBTID.csv ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/etc/TPA2051_CFG.csv ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/etc/TPA2051_CFG_XC.csv ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/etc/firmware/BCM4329B1_OO2.002.023.0589.0632.hcd ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/etc/voicemail-conf.xml ../../../vendor/htc/$DEVICE/
adb pull /system/etc/spn-conf.xml ../../../vendor/htc/$DEVICE/
adb pull /system/etc/firmware/fw_bcm4329.bin ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/etc/firmware/fw_bcm4329_apasta.bin ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/etc/firmware/leia_pfp_470.fw ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/etc/firmware/leia_pm4_470.fw ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/etc/firmware/vidc_1080p.fw ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/lib/egl/libEGL_adreno200.so ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/lib/egl/libGLESv1_CM_adreno200.so ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/lib/egl/libGLESv2_adreno200.so ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/lib/egl/libq3dtools_adreno200.so ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/lib/libOmxVdec.so ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/lib/libgsl.so ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/lib/libhtc_acoustic.so ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/lib/libhtc_ril.so ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/usr/keylayout/qwerty.kl ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/usr/keylayout/pyramid-keypad.kl ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/usr/keylayout/h2w_headset.kl ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/usr/keylayout/BT_HID.kl ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/usr/keylayout/AVRCP.kl ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/usr/keychars/qwerty2.kcm.bin ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/usr/keychars/qwerty.kcm.bin ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/usr/keychars/pyramid-keypad.kcm.bin ../../../vendor/htc/$DEVICE/proprietary
adb pull /system/usr/keychars/BT_HID.kcm.bin ../../../vendor/htc/$DEVICE/proprietary

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/htc/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/__DEVICE__/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \\
    vendor/htc/__DEVICE__/proprietary/libcamera.so:obj/lib/libcamera.so

# All the blobs necessary for pyramid
PRODUCT_COPY_FILES += \\
    vendor/htc/__DEVICE__/proprietary/akmd:/system/bin/akmd \\
    vendor/htc/__DEVICE__/proprietary/snd8x60:/system/bin/snd8x60 \\
    vendor/htc/__DEVICE__/proprietary/AdieHWCodecSetting.csv:/system/etc/AdieHWCodecSetting.csv \\
    vendor/htc/__DEVICE__/proprietary/AudioBTID.csv:/system/etc/AudioBTID.csv \\
    vendor/htc/__DEVICE__/proprietary/TPA2051_CFG_XC.csv:/system/etc/TPA2051_CFG_XC.csv \\
    vendor/htc/__DEVICE__/proprietary/TPA2051_CFG.csv:/system/etc/TPA2051_CFG.csv \\
    vendor/htc/__DEVICE__/proprietary/WPDB.zip:/system/etc/WPDB.zip \\
    vendor/htc/__DEVICE__/proprietary/BCM4329B1_OO2.002.023.0589.0632.hcd:/system/etc/BCM4329B1_OO2.002.023.0589.0632.hcd \\
    vendor/htc/__DEVICE__/proprietary/fw_bcm4329.bin:/system/etc/firmware/fw_bcm4329.bin \\
    vendor/htc/__DEVICE__/proprietary/fw_bcm4329_apsta.bin:/system/etc/firmware/fw_bcm4329_apsta.bin \\
    vendor/htc/__DEVICE__/proprietary/leia_pfp_470.fw:/system/etc/firmware/leia_pfp_470.fw \\
    vendor/htc/__DEVICE__/proprietary/leia_pm4_470.fw:/system/etc/firmware/leia_pm4_470.fw \\
    vendor/htc/__DEVICE__/proprietary/vidc_1080p.fw:/system/etc/firmware/vidc_1080p.fw \\
    vendor/htc/__DEVICE__/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \\
    vendor/htc/__DEVICE__/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \\
    vendor/htc/__DEVICE__/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \\
    vendor/htc/__DEVICE__/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \\
    vendor/htc/__DEVICE__/proprietary/libOmxVdec.so:/system/lib/libOmxVdec.so \\
    vendor/htc/__DEVICE__/proprietary/libcamera.so:/system/lib/libcamera.so \\
    vendor/htc/__DEVICE__/proprietary/libgsl.so:/system/lib/libgsl.so \\
    vendor/htc/__DEVICE__/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \\
    vendor/htc/__DEVICE__/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so \\
    vendor/htc/__DEVICE__/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \\
    vendor/htc/__DEVICE__/proprietary/liboemcamera.so:/system/lib/libcamera.so \\
    vendor/htc/__DEVICE__/proprietary/liboemcamera.so:/system/lib/libcamera_client.so \\
    vendor/htc/__DEVICE__/proprietary/liboemcamera.so:/system/lib/libCamera_gingerbread.so \\
    vendor/htc/__DEVICE__/proprietary/liboemcamera.so:/system/lib/libcameraservice.so \\

EOF

./setup-makefiles.sh
